### PR TITLE
Main activity and splash screen landscape orientation

### PR DESCRIPTION
**Pull request by SadhanaAnandan**
The main activity was made into landscape again, as the code was not there. The splash screen's orientation was also changed into landscape. Anasha Sarker and Sadhana  Anandan worked on this code. @AnashaSarker2001

### CODE REVIEW

**Review by AnashaSarker2001 — APPROVED** [review]
Good work

**Review by platisd — CHANGES_REQUESTED** [review]
How do you know this works on everyone's computers?

**Comment by AnashaSarker2001** [comment]
Android studios and SMCE would crash if I had both on but it works on others.

**Comment by platisd** [comment]
> Android studios and SMCE would crash if I had both on but it works on others.

So we will need to take your word for it and there's no guarantee that future changes will not break something.
Please fix #40 so you can _prove_ that what you are introducing works and will keep working.

**Pull request merged**
