### PR TITLE
Removed cmake-build-debug

### PR DESCRIPTION
**Pull request by Gussamanel**
Deleted cmake-build-debug from the project.

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Review by shahdmetwally — APPROVED** [review]
The file has been removed therefore our Arduino CI should be fixed now.

**Comment by platisd** [comment]
> The file has been removed therefore our Arduino CI should be fixed now.

No it's not, you coincidentally passed by the check because you were using an old `HEAD` of the `master` branch. Maybe I should do something about that too if you try to abuse this loophole! haha :D

**Comment by shahdmetwally** [comment]
We don't mean to abuse any loopholes we just didn't know. Maybe you can explain to us where we went wrong.

**Comment by platisd** [comment]
Yes I know you weren't doing this on purpose. I am kidding. :) 
You have a few more tasks before #80 is finished. I added them to the issue. Make sure you are on the _latest_ `master` branch before branching off.

**Pull request merged**
